### ISSUE TITLE
[BUG] Problem that nodes and edges dissappear sometimes

### ISSUE THREAD

**Issue by pdolif** [rwth-acis/CAE-SyncMeta-Additions#35]
1. **Summary** Sometimes when opening the modeling space, some nodes and/or edges seem to disappear and are not part of the displayed model anymore.
2. **Bug Details**
   1. **What?** Nodes/edges seem to get lost when model gets uploaded into Yjs room.
   2. **Where?** It occurs at for microservices and also for frontend components.
   3. **When?/How often?** Bug occurs, when the modeling is "reopened" by using the project management.
   4. **How?/Current state** Here is a step by step guide to reproduce the bug:
      - Create a new microservice in a project.
      - Open the modeling of the microservice, then model an example microservice and commit the changes in the CAE.
      - Go back to the project management and then "rejoin" the modeling space of the microservice. Important: Do not use the top menu for this, because there the model is not really "reuploaded". Use the "join modeling" button in the project management instead.
      - Now some of the nodes and edges are not shown in the model. It is still possible to click on the "remove changes since last commit" button, then the full model is back again. But of course, this bug should not occur.
3. **Fixed state** No nodes or edges should disappear when reloading the model by joining the modeling space again.

**Comment by pdolif** [comment]
Update:
If you reopened the component and undo the changes, then the correct model gets shown, but the deletions of nodes and edges are still shown in the versioning widget.

**Comment by pdolif** [comment]
By using some extra debug log messages, I could find out the following:
When the component gets reopened by using the project management, the model in the Yjs room is incorrect and some nodes and edges are missing.
When you then click on "undo changes since last commit", the correct model gets set into the y.share.data map here: https://github.com/rwth-acis/CAE-Frontend/blob/develop/cae-app/src/versioning/commit-details.js#L983.
But after that, when we call the ReloadWidgetOperation (here: https://github.com/rwth-acis/CAE-Frontend/blob/develop/cae-app/src/versioning/commit-details.js#L986) the model gets changed again and nodes and edges are missing.
If line 986 gets removed, then the model in the Yjs room does not change and remains correct, but then also the Canvas does not get updated.
Maybe there is a problem with the ReloadWidgetOperation in SyncMeta.

**Comment by pdolif** [comment]
Before the following line gets called in SyncMeta, y.share.data.get("model") still contains all the nodes, but after it gets called some nodes are missing:
https://github.com/rwth-acis/syncmeta/blob/aec58d3548ed027c88cd6a9663088b47d99e9d7a/widgets/src/js/main_widget.js#L660

**Comment by pdolif** [comment]
If the Yjs docker container gets restarted, then opening and reopening of the component works perfect again and no nodes or edges are missing.

**Comment by pdolif** [comment]
As long as no column has been added, the error does not appear to occur. Since you cannot add a table without a column, the problem could also be reasoned in database tables, but this cannot be tested without adding a column.

**Comment by pdolif** [comment]
Bug also appears when ReloadWidgetOperation is not called.
When modeling without creating a new commit, after reloading the page multiple times, edges disappear.

**Comment by pdolif** [comment]
I've done another "experiment":
Disable all the widgets except the canvas and property browser. This ensures that the bug is not reasoned by any other widget of the CAE.
Then add a RESTResource, a database, a table and a column. Connect all of them.
You can reload multiple times - nothing happens. The bug does not occur.
Note: Until now, all the attributes of the nodes are currently not set / changed from the default ones.
When we now select the column to be a primary key and reload the page two times, the bug occurs and all edges disappear.

Update: The bug also occurs in the frontend modeling, but it has not yet been noticed there, because it seems to occur only when a checkbox of a nodes attributes gets checked.

Update 2: Bug also occurs when using master branch of SyncMeta instead of ba-philipp branch.

**Comment by pdolif** [comment]
It seems that only the edges and nodes that were added after the column disappear.

**Comment by pdolif** [comment]
I could now also reproduce the bug in the main CAE instance which is currently running. This shows, that the bug is not related to the changes of the ba-philipp branch.

**Comment by pdolif** [comment]
Here is a more detailed description of when the bug occurs:
The bug occurs after changing the value of a checkbox attribute and all the edges and nodes that were added after the modeling element where a boolean attribute has changed disappear (after reloading the page 2 times).

**Comment by pdolif** [comment]
Bug also occurs when running SyncMeta only, i.e. without the CAE extension by just using the rwthacis/syncmeta docker image.
Bug is also not depending on the specific metamodels of the CAE and also occurs with different metamodels.

Bug also only occurs when the user who creates the modeling elements is logged in.

**Comment by pdolif** [comment]
New approach: Try to update SyncMeta to latest Yjs version.

When using the latest available versions of all Yjs components, we get the error message, that y-map requires a Yjs version lower than 13. Since that, using the latest Yjs version is not possible.
When resolving this conflict, we get the following dependency versions in bower:
```
"y-array": "^10.1.4",
"y-map": "^10.1.3",
"y-memory": "^8.0.9",
"y-text": "^9.5.1",
"y-websockets-client": "^8.0.16",
"yjs": "^12.3.3"
```
With these versions the bug in SyncMeta still occurs.
Updating to Yjs 13 seems to be more complicated, since the structure seems to have changed a lot.

**Comment by pdolif** [comment]
Another point I found out:
Steps to reproduce:
1. Open a new empty SyncMeta space **without** logging in (anonymous user)
2. Open meta-model editor, add an "Object", give it a label and add a boolean attribute to it.
3. Click on "Generate Metamodel"
4. Open model editor, add the object once, set the boolean value to true and after that add another object (but don't change the boolean value).
5. When reloading the browser page, a "ValueChangeOperation" get created here: https://github.com/rwth-acis/syncmeta/blob/master/widgets/src/js/operations/OperationFactory.js#L263
This operation looks like this:
```
{
    entityId: "6ba22e68b7cf012b78878c4f[sds]",
    value: true,
    position: null,
    type: "update",
    jabberId: undefined
}
```
6. Now login with a learning layers account. When reloading the page, the ValueChangeOperation still gets created.
7. Change the boolean value of the first node from "true" to "false". After reloading the page, the ValueChangeOperation is not called anymore. When reloading a second time, the second node disappears.

Edit: Maybe it has something to do with this if statement: https://github.com/rwth-acis/syncmeta/blob/master/widgets/src/js/canvas_widget/BooleanValue.js#L136?

**Comment by pdolif** [comment]
Just to keep this issue up-to-date:

Summary: Based on my current understanding, when reloading the page, the JSONtoGraph function creates the nodes and edges which are part of the JSON model.
During the for-loop which iterates over all the nodes from the model and adds them to the graph, at some point the event listener of BooleanValue is called and calls the "save-function".
The entity manager then calls graphToJSON to create a JSON model from the current graph. Since this graph does not contain all the nodes and edges yet, an incorrect model is stored in Yjs.
This leds to the bug, that when we reload the page again, the incorrect model is used and some edges and nodes are missing.
Also very interesting is, that when we compare the registerYType function of both the BooleanValue and as an example the IntegerValue, then the one from IntegerValue looks the same but there's one difference: The function call of "save" is missing.

**Comment by pdolif** [comment]
In the IntegerValue the function call of "save" is not really missing, it is just placed inside a debounce function (see https://github.com/rwth-acis/syncmeta/blob/master/widgets/src/js/canvas_widget/IntegerValue.js#L160).
This ensures that the end of e.g. the createNodes function in JSONtoGraph is reached before the save-function is called.
Thus, the model is fully put into the graph when save is called and the bug does not occur.

For the BooleanValue we can also move the save-function call into a debounce function. This solves the problem.

**Comment by pdolif** [comment]
Commit that fixes the bug in SyncMeta can be found here: https://github.com/rwth-acis/syncmeta/commit/7787ef0244ad210f3c1aa592ff8c8016e5abe76e

**Comment by pedela** [comment]
So this issue can be resolved?
