### ISSUE TITLE
Investigate Docker image size 

### ISSUE THREAD

**Issue by pdolif** [rwth-acis/CAE-SyncMeta-Additions#47]
The size of the CAE-Frontend docker image is very large. Investigate what this is due to.

**Comment by pdolif** [comment]
The base image (node:8) is already ~900mb large. Switching to node:8-alpine is not possible without any other problems occuring.
Nginx or supervisord then do not run properly.

Additional things that get installed (e.g. supervisor, nginx, grunt and polymer) are around ~680mb.
npm install in the cae-app folder adds 50mb.
npm install in the widgets folder of the CAE adds 415mb.
npm install in the syncmeta folder adds 210mb.
npm install in the syncmeta/widgets folder adds 150mb.
Cloning the WireframingEditor only adds ~8mb and npm install there adds 212mb.

**Comment by pdolif** [comment]
I tried a bit more with the alpine based node image and got it running now (https://github.com/rwth-acis/CAE-Frontend/commit/54deb95981dbe170ebb2f318227bdd2e0258fd10).
Some additional installs (e.g. python) were required, the config file names for supervisor changed and the /run/nginx folder needs to be created manually (in the Dockerfile).
Now the image size shrunk to 1.87GB (from previous 2.64GB).

**Comment by pedela** [comment]
From my point of view, this issue can be closed, good work.
